#!/bin/bash -l

# execute this script in directory intended for log and html files
# e.g. in crontab
# 17 * * * * { { cd /home/huck/mpcite && PATH=/usr/local/bin:$PATH:/home/huck/.local/bin ./scripts/run_mpcite 1 && PATH=/usr/local/bin:$PATH rsync -av index.html matgen7:/var/www/mpcite | sed '0,/^$/d' ; } >> /home/huck/mpcite/mpcite.log ; } 2>&1 | tee -a /home/huck/mpcite/mpcite.log

if [[ $# -ne 1 || $1 == "-h" ]]; then
  echo "Usage: `basename $0` num_materials"
  exit 0
fi

source `which virtualenvwrapper.sh`
workon env_mpcite
command -v mpcite >/dev/null 2>&1 || { echo >&2 "mpcite not installed. Abort."; exit 1; }

mpcite -v info
mpcite build
mpcite submit -a $1
mpcite monitor --div-only -o index.html

deactivate
