#!/bin/bash -l

# execute this script in directory intended for log and html files
# e.g. in crontab
# */60 * * * * { { cd /global/homes/m/matcomp/mpcite && ./scripts/run_mpcite 0 ; } >> /global/homes/m/matcomp/mpcite/mpcite.log ; } 2>&1 | tee -a /global/homes/m/matcomp/mpcite/mpcite.log

if [[ $# -ne 1 || $1 == "-h" ]]; then
  echo "Usage: `basename $0` num_materials"
  exit 0
fi

source `which virtualenvwrapper.sh`
workon env_mpcite
command -v mpcite >/dev/null 2>&1 || { echo >&2 "mpcite not installed. Abort."; exit 1; }

mpcite -v info
mpcite build
mpcite submit -a $1
mpcite monitor # save mpcite.html to current dir

deactivate
