name: linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
<<<<<<< HEAD
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set up the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          version: "latest"

      - name: Analyzing the code with ruff
        run: uvx ruff check --output-format=github
=======
# TODO: setup linting with uv/ruff
>>>>>>> 52382ff (Merged upstream (#1))
