name: testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11", "3.12", "3.13"]

    name: mp-cite (${{ matrix.os }}/py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        env:
          ELINK_REVIEW_API_TOKEN: ${{ secrets.ELINK_REVIEW_API_TOKEN }}
          ELINK_REVIEW_ENDPOINT: ${{ secrets.ELINK_REVIEW_ENDPOINT }}
        run: uv run pytest tests
# codecov?
